steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: '01-hello-world-rest-api'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ashrith-sandbox/cloudbuild-java-hello-world', '.']
  dir: '01-hello-world-rest-api'
images: ['gcr.io/ashrith-sandbox/cloudbuild-java-hello-world']