steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  dir: '01-hello-world-rest-api'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ashrith-sandbox/test-docker-repo/cloudbuild-java-hello-world', '.']
  dir: '01-hello-world-rest-api'
images: ['us-central1-docker.pkg.dev/ashrith-sandbox/test-docker-repo/cloudbuild-java-hello-world']